name: compile_and_test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# If you want to run it manually you would add "worflow_dispatch"
  workflow_dispatch:
  
# defaults:
#   run:
#     shell: bash  
 
# Jobs are run separately and will spin up a new build machine for each sub-item
jobs:
  # Under jobs you can put whatever name you want
  # This is just a custom name "build" but it can be anything
  build:
    name: Compile and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libgsl-dev libsundials-dev petsc-dev slepc-dev
      
      - name: Bootstrap with autoconf
        run: ./autogen.sh
        
      - name: Configure
        run: ./configure

      - name: Compile
        run: make
        
      - name: Run tests
        run: make check
